[package]
name = "rest"
version = "0.1.0"
authors = ["Igor Ying Zhang <igor_zhangying@fudan.edu.cn>"]
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1"
time = "0.1.12"
clap = "3.0.0-beta.2"
regex = "0.1.41"
itertools = "0.8"
serde_json = "1.0"
serde = {version="1.0",features=["derive"]}
num-complex = "0.4"
libc = "0.2"
#hdf5 = "0.8.0"
hdf5-metno = "0.10.1"
chrono = "0.4"
#jemallocator = "0.3.2"
mimalloc = "0.1.43"
rayon = "1.8"
crossbeam = "0.8"
libm = "0.2"
blas-sys = "0.7"
blas = "0.22"
lazy_static = "1.4"
toml = "0.7"
#tuple-conv = "1.0.1"
num-traits = "0.2.15"
statrs = "0.13"
rand = "0.3"
array_tool = "1.0.3"
fuzzy-matcher = "0.3.7"
ndarray = "0.15.6"
# for libecpint
cxx = "1.0"
autocxx = "0.26.0"
miette = "5.0"
#katex-doc = "0.1.0"
#rust_libecpint = {path="../rust_libecpint"}
# seems to pull in libssl and libcrypto which is rejected by manylinux
reqwest = { version = "0.10", default-features = false, features = ["blocking", "json"] }
mpi = {version = "0.8.0", features = ["user-operations", "derive"]}
# for cuda
#cudarc = "0.10.0"
rest_tensors = {path="../rest_tensors"}
rest_libcint = {path="../rest_libcint"}
#liblbfgs = {path="../rust-lbfgs"}
liblbfgs = "0.1.0"
sysinfo = "0.33"
rstsr = { version = "0.2.6", default-features = false, features = ["openblas", "linalg", "rayon", "std", "col_major"] }
rstsr-openblas = { version = "0.2.6", features = ["linalg", "openmp"] }
derive_builder = { version = "0.20" }

[build-dependencies]
autocxx-build = "0.26.0"
miette = { version = "5", features = ["fancy"]}
dunce = "1.0.0"


[dependencies.pyo3]
version = "0.21.1"
features = ["extension-module"]

#[package.metadata.docs.rs]
#rustdoc-args = [
#    "--html-in-header",
#    #".cargo/registry/src/github.com-1ecc6299db9ec823/katex-doc-0.1.0/katex.html",
#    "/share/home/tygao/REST3.0/rest/katex.html",
#]

[dev-dependencies]
criterion = "0.4"


[[bench]]
name = "bench_tensors"
harness = false


[[bin]]
name = "rest"
path = "src/main.rs"

# for pyrest
[lib]
name = "pyrest"
path = "src/lib.rs"
crate-type=["cdylib","lib"]
